version: '3.8'

services:
  chopsticks-asset-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chopsticks-asset-hub
    ports:
      - "9000:9000"
    volumes:
      - ./pd-ah.yml:/app/config.yml
    command: ["chopsticks", "-c", "/app/config.yml", "-p", "9000", "--addr", "0.0.0.0"]
    networks:
      - kalatori-network

networks:
  kalatori-network:
    external: true
