use thiserror::Error;
use uuid::Uuid;

use crate::types::WebhookEvent;

use super::DaoExecutor;

#[derive(Debug, Error)]
pub enum DaoWebhookEventError {
    #[error("Database error during webhook event operation")]
    DatabaseError,
}

pub trait DaoWebhookEventMethods: DaoExecutor + 'static {
    async fn create_webhook_event(
        &self,
        event: impl Into<WebhookEvent>,
    ) -> Result<WebhookEvent, DaoWebhookEventError> {
        let event = event.into();

        let query = sqlx::query_as::<_, WebhookEvent>(
            "INSERT INTO webhook_events (id, entity_id, payload, sent, created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?)
             RETURNING *",
        )
        .bind(event.id)
        .bind(event.entity_id)
        .bind(event.payload)
        .bind(event.sent)
        .bind(event.created_at)
        .bind(event.updated_at);

        self.fetch_one(query)
            .await
            .map_err(|e| {
                tracing::debug!(
                    error.category = "dao.webhook_event",
                    error.operation = "create_webhook_event",
                    error.source = ?e,
                    event.id = %event.id,
                    event.entity_id = %event.entity_id,
                    "Failed to create webhook event"
                );

                DaoWebhookEventError::DatabaseError
            })
    }

    async fn get_webhook_events_to_send(
        &self,
        limit: u32,
    ) -> Result<Vec<WebhookEvent>, DaoWebhookEventError> {
        if limit == 0 {
            return Ok(Vec::new());
        }

        let query = sqlx::query_as::<_, WebhookEvent>(
            "WITH ranked_events AS (
              SELECT
                id,
                entity_id,
                payload,
                sent,
                created_at,
                updated_at,
                ROW_NUMBER() OVER (
                  PARTITION BY entity_id
                  ORDER BY created_at ASC, id ASC
                ) as rn
              FROM webhook_events
              WHERE sent = 0
            )
            SELECT id, entity_id, payload, sent, created_at, updated_at
            FROM ranked_events
            WHERE rn = 1
            ORDER BY created_at ASC, id ASC
            LIMIT ?;",
        )
        .bind(limit);

        self.fetch_all(query)
            .await
            .map_err(|_| DaoWebhookEventError::DatabaseError)
    }

    async fn mark_webhook_event_as_sent(
        &self,
        event_id: Uuid,
    ) -> Result<WebhookEvent, DaoWebhookEventError> {
        let query = sqlx::query_as::<_, WebhookEvent>(
            "UPDATE webhook_events
             SET sent = 1, updated_at = ?
             WHERE id = ?
             RETURNING *",
        )
        .bind(chrono::Utc::now().naive_utc())
        .bind(event_id);

        self.fetch_one(query)
            .await
            .map_err(|_| DaoWebhookEventError::DatabaseError)
    }
}

impl<T: DaoExecutor + 'static> DaoWebhookEventMethods for T {}

// TODO: review and probably rewrite tests. They were generated by AI and
// reviewed only superficially.
#[cfg(test)]
mod tests {
    use chrono::Utc;

    use crate::dao::create_test_dao;
    use crate::types::{
        PublicInvoice,
        default_webhook_event,
    };

    use super::*;

    #[tokio::test]
    async fn test_create_webhook_event() {
        let dao = create_test_dao().await;

        let invoice_id = Uuid::new_v4();

        // Create a webhook event for this invoice
        let event = default_webhook_event(invoice_id);
        let event_id = event.id;
        let event_timestamp = event.timestamp;

        let webhook_event = dao
            .create_webhook_event(event)
            .await
            .unwrap();

        // Verify the webhook event was created correctly
        assert_eq!(webhook_event.id, event_id);
        assert!(!webhook_event.sent);
        assert_eq!(
            webhook_event.created_at,
            event_timestamp
        );
        assert_eq!(
            webhook_event.updated_at,
            event_timestamp
        );

        // Verify the payload can be deserialized
        let deserialized: crate::types::GenericEvent<PublicInvoice> =
            serde_json::from_value(webhook_event.payload).unwrap();
        assert_eq!(deserialized.id, event_id);
        assert_eq!(deserialized.payload.id, invoice_id);
    }

    #[tokio::test]
    async fn test_get_webhook_events_to_send_empty() {
        let dao = create_test_dao().await;

        let events = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        assert_eq!(events.len(), 0);
    }

    #[tokio::test]
    async fn test_get_webhook_events_to_send_filters_sent_events() {
        let dao = create_test_dao().await;

        let invoice_id = Uuid::new_v4();

        // Create an unsent event
        let event1 = default_webhook_event(invoice_id);
        let event1_id = event1.id;
        dao.create_webhook_event(event1)
            .await
            .unwrap();

        // Create another event and mark it as sent
        let event2 = default_webhook_event(invoice_id);
        let event2_id = event2.id;
        dao.create_webhook_event(event2)
            .await
            .unwrap();
        dao.mark_webhook_event_as_sent(event2_id)
            .await
            .unwrap();

        // Get events to send - should only return the unsent event
        let events = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].id, event1_id);
        assert!(!events[0].sent);
    }

    #[tokio::test]
    async fn test_get_webhook_events_to_send_one_per_entity() {
        let dao = create_test_dao().await;

        let invoice1_id = Uuid::new_v4();
        let invoice2_id = Uuid::new_v4();

        // Create 3 events for invoice1 (different timestamps)
        let event1_oldest = default_webhook_event(invoice1_id);
        let event1_oldest_id = event1_oldest.id;
        dao.create_webhook_event(event1_oldest)
            .await
            .unwrap();

        tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;
        let event1_middle = default_webhook_event(invoice1_id);
        dao.create_webhook_event(event1_middle)
            .await
            .unwrap();

        tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;
        let event1_newest = default_webhook_event(invoice1_id);
        dao.create_webhook_event(event1_newest)
            .await
            .unwrap();

        // Create 2 events for invoice2
        tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;
        let event2_oldest = default_webhook_event(invoice2_id);
        let event2_oldest_id = event2_oldest.id;
        dao.create_webhook_event(event2_oldest)
            .await
            .unwrap();

        tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;
        let event2_newest = default_webhook_event(invoice2_id);
        dao.create_webhook_event(event2_newest)
            .await
            .unwrap();

        // Get events to send - should return oldest event per invoice
        let events = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        assert_eq!(events.len(), 2);

        // Should be sorted by created_at, so invoice1's oldest event first
        assert_eq!(events[0].id, event1_oldest_id);
        assert_eq!(events[1].id, event2_oldest_id);

        // Verify they're not sent yet
        assert!(!events[0].sent);
        assert!(!events[1].sent);
    }

    #[tokio::test]
    async fn test_get_webhook_events_to_send_respects_limit() {
        let dao = create_test_dao().await;

        // Create 5 different invoices with 1 event each
        for _ in 0..5 {
            tokio::time::sleep(tokio::time::Duration::from_millis(5)).await;
            let event = default_webhook_event(Uuid::new_v4());
            dao.create_webhook_event(event)
                .await
                .unwrap();
        }

        // Request only 3 events
        let events = dao
            .get_webhook_events_to_send(3)
            .await
            .unwrap();
        assert_eq!(events.len(), 3);

        // All should be unsent
        assert!(events.iter().all(|e| !e.sent));
    }

    #[tokio::test]
    async fn test_get_webhook_events_to_send_deterministic_ordering() {
        let dao = create_test_dao().await;

        // Create multiple events with the exact same timestamp
        let timestamp = Utc::now();
        let mut event_ids = Vec::new();
        let invoice_id = Uuid::new_v4();

        for _ in 0..3 {
            let mut event = default_webhook_event(invoice_id);
            event.timestamp = timestamp; // Force same timestamp
            event_ids.push(event.id);
            dao.create_webhook_event(event)
                .await
                .unwrap();
        }

        // Get events to send multiple times - should always return the same event
        // (lowest id)
        let events1 = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        let events2 = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        let events3 = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();

        assert_eq!(events1.len(), 1);
        assert_eq!(events2.len(), 1);
        assert_eq!(events3.len(), 1);

        // All should return the same event
        assert_eq!(events1[0].id, events2[0].id);
        assert_eq!(events2[0].id, events3[0].id);

        // Should be the one with the smallest UUID (due to ORDER BY id ASC
        // tie-breaking)
        let mut sorted_ids = event_ids.clone();
        sorted_ids.sort();
        assert_eq!(events1[0].id, sorted_ids[0]);
    }

    #[tokio::test]
    async fn test_mark_webhook_event_as_sent() {
        let dao = create_test_dao().await;

        let event = default_webhook_event(Uuid::new_v4());
        let event_id = event.id;
        let original_timestamp = event.timestamp;

        let created = dao
            .create_webhook_event(event)
            .await
            .unwrap();
        assert!(!created.sent);
        assert_eq!(created.created_at, original_timestamp);
        assert_eq!(created.updated_at, original_timestamp);

        // Small delay to ensure updated_at will be different
        tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;

        // Mark as sent
        let updated = dao
            .mark_webhook_event_as_sent(event_id)
            .await
            .unwrap();

        // Verify it's marked as sent
        assert!(updated.sent);
        assert_eq!(updated.id, event_id);

        // Verify timestamps
        assert_eq!(updated.created_at, original_timestamp); // created_at unchanged
        assert!(updated.updated_at > original_timestamp); // updated_at changed

        // Verify it no longer appears in get_webhook_events_to_send
        let events = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        assert_eq!(events.len(), 0);
    }

    #[tokio::test]
    async fn test_mark_webhook_event_as_sent_after_marking_next_event_appears() {
        let dao = create_test_dao().await;

        let invoice_id = Uuid::new_v4();

        // Create 3 events for the same invoice
        let event1 = default_webhook_event(invoice_id);
        let event1_id = event1.id;
        dao.create_webhook_event(event1)
            .await
            .unwrap();

        tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;

        let event2 = default_webhook_event(invoice_id);
        let event2_id = event2.id;
        dao.create_webhook_event(event2)
            .await
            .unwrap();

        tokio::time::sleep(tokio::time::Duration::from_millis(10)).await;

        let event3 = default_webhook_event(invoice_id);
        let event3_id = event3.id;
        dao.create_webhook_event(event3)
            .await
            .unwrap();

        // Get first event to send
        let events = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].id, event1_id);

        // Mark first event as sent
        dao.mark_webhook_event_as_sent(event1_id)
            .await
            .unwrap();

        // Get next event - should now return event2
        let events = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].id, event2_id);

        // Mark second event as sent
        dao.mark_webhook_event_as_sent(event2_id)
            .await
            .unwrap();

        // Get next event - should now return event3
        let events = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].id, event3_id);

        // Mark third event as sent
        dao.mark_webhook_event_as_sent(event3_id)
            .await
            .unwrap();

        // No more events to send
        let events = dao
            .get_webhook_events_to_send(10)
            .await
            .unwrap();
        assert_eq!(events.len(), 0);
    }
}
