account-lifetime = 604800000 # 1 week.
debug = true
depth = 86400000 # 1 day.

[chain]
name = "statemint"
endpoints = [
    "wss://polkadot-asset-hub-rpc.polkadot.io",
    "wss://statemint-rpc.dwellir.com",
]

[[chain.assets]]
name = "USDC"
id = 1337

[[chain.assets]]
name = "USDt"
id = 1984
