account-lifetime = 604800000 # 1 week.
debug = true
depth = 86400000 # 1 day.

[chain]
name = "statemint"
endpoint = "wss://polkadot-asset-hub-rpc.polkadot.io"

[[chain.assets]]
name = "USDC"
id = 1337

[[chain.assets]]
name = "USDt"
id = 1984
