account-lifetime = 86400000 # 1 day.
depth = 3600000 # 1 hour.
debug = true

[chain]
name = "statemint"
endpoint = "ws://localhost:9000"

[[chain.assets]]
name = "USDC"
id = 1337

[[chain.assets]]
name = "USDt"
id = 1984
