account-lifetime = 86400000 # 1 day.
depth = 3600000 # 1 hour.
debug = true
in-memory-db = true

[chain]
name = "westmint"
endpoint = "wss://westend-asset-hub-rpc.polkadot.io"

[[chain.assets]]
name = "JOE"
id = 8

[[chain.assets]]
name = "TEST"
id = 1234